version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  reviewers:
  - samueldple
  assignees:
  - samueldple
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
